ekimeidatanew/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

from rest_framework import routers
router = routers.DefaultRouter()
# router.register('station', views.StationViewSet)
# router.register('line/<int:pref_cd>', views.LineViewSet.as_view(), base_name='lines')
urlpatterns = router.urls

app_name = 'ekimeidatanew'

urlpatterns = [
	path('line/<int:line_code>/', views.StationListbyLineView.as_view(), name='stationlistbylineview'),
	path('lineservice/<slug:line_service_code>/', views.StationServiceListbyLineView.as_view(), name='stationservicelistbylineview'),
	path('linelist/', views.LineServiceListbyCompanyView.as_view(), name='lineservicelistbycompanyview'),
	path('stationsearch/', views.StationSearchView.as_view(), name='stationsearchview'),
	path('upload/', views.uploadStation, name='uploadStation'),
	path('uploadline/', views.uploadLine, name='uploadLine'),
	path('uploadcompany/', views.uploadCompany, name='uploadCompany'),
	path('uploadrailwaytype/', views.uploadRailwayType, name='uploadRailwayType'),
	path('uploadstationservice/', views.uploadStationService, name='uploadStationService'),
	path('uploadlineservice/', views.uploadLineService, name='uploadLineService'),
	path('stationdelete/', views.StationDelete, name='StationDelete'),
	path('linedelete/', views.LineDelete, name='LineDelete'),
	path('companydelete/', views.CompanyDelete, name='CompanyDelete'),
	path('stationservicedelete/', views.StationServiceDelete, name='StationServiceDelete'),
	path('lineservicedelete/', views.LineServiceDelete, name='LineServiceDelete'),
	path('notice/', views.NoticeView.as_view(), name='notice'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekimei1/', include('ekimei1.urls'), name='ekimei1'),
    path('ekimeidatanew/', include('ekimeidatanew.urls'), name='ekimeidatanew'),
]

ekimeidatanew/views.py
from django.shortcuts import render
from django.views import generic
from .models import Railway_type, Company, Line, Station, LineService, StationService
import csv
from io import TextIOWrapper

# Create your views here.
def uploadStation(request):
	if 'csv' in request.FILES:
		stations = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		i = 0
		for line in csv_file:
			if i != 0:
				station_code = line[2]
				station_group_code = line[3]
				station_name = line[6]
				station_name_kana = line[7]
				station_name_en = line[8]
				railway_type = line[9]
				line_name = line[10]
				line_code = Line.objects.get(line_code=line[11])
				if line[12] != '':
					sort_by_line = line[12]
				else:
					sort_by_line = None;
				if line[14] != '':
					pref_cd_old = line[14]
				else:
					pref_cd_old = None;
				post_old = line[15]
				add_old = line[16]
				lon_old = line[17]
				lat_old = line[18]
				if line[19] != '':
					open_ymd_old = line[19]
				else:
					open_ymd_old = None;
				if line[20] != '':
					close_ymd_old = line[20]
				else:
					close_ymd_old = None;
				if line[21] != '':
					e_status_old = line[21]
				else:
					e_status_old = None;
				if line[22] != '':
					e_sort_old = line[22]
				else:
					e_sort_old = None;
				if line[23] != '':
					sort = line[23]
				else:
					sort = None;

				station = Station(
					station_code=station_code,
					station_group_code=station_group_code,
					station_name=station_name,
					station_name_kana=station_name_kana,
					station_name_en=station_name_en,
					railway_type=railway_type,
					line_name=line_name, 
					line_code=line_code,
					sort_by_line=sort_by_line,
					pref_cd_old=pref_cd_old,
					post_old=post_old,
					add_old=add_old,
					lon_old=lon_old,
					lat_old=lat_old,
					open_ymd_old=open_ymd_old,
					close_ymd_old=close_ymd_old,
					e_status_old=e_status_old,
					e_sort_old=e_sort_old,
					sort=sort)
				stations.append(station)
			else:
				i+=1
		Station.objects.bulk_create(stations)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def uploadLine(request):
	if 'csv' in request.FILES:
		lines = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		i = 0
		for line in csv_file:
			if i != 0:
				railway_type_name = line[0]
				line_code = line[1]
				line_group_code = line[2]
				line_name_formal = line[3]
				line_name = line[4]
				line_name_sub = line[5]
				company_code = Company.objects.get(company_code=line[6])
				sort_by_company = line[7]
				start_station = line[8]
				end_station = line[9]
				business_type = line[10]
				is_freight = line[11]
				l = Line(
					railway_type_name=railway_type_name,
					line_code=line_code,
					line_group_code=line_group_code,
					line_name_formal=line_name_formal,
					line_name=line_name,
					line_name_sub=line_name_sub,
					company_code=company_code,
					sort_by_company=sort_by_company,
					start_station=start_station,
					end_station=end_station,
					business_type=business_type,
					is_freight=is_freight)
				lines.append(l)
			else:
				i+=1
		Line.objects.bulk_create(lines)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def uploadCompany(request):
	if 'csv' in request.FILES:
		companies = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		i = 0
		for line in csv_file:
			if i != 0:
				railway_type_name = line[0]
				railway_type_code = line[1]
				company_code = line[2]
				company_name = line[3]
				company_name_short = line[4]
				company_name_short_2 = line[5]
				company_name_kana = line[6]
				company_color = line[7]
				area_code = line[8]
				sort_by_area = line[9]
				company = Company(
					railway_type_name=railway_type_name,
					railway_type_code=railway_type_code,
					company_code=company_code,
					company_name=company_name,
					company_name_short=company_name_short,
					company_name_short_2=company_name_short_2,
					company_name_kana=company_name_kana,
					company_color=company_color,
					area_code=area_code,
					sort_by_area=sort_by_area)
				companies.append(company)
			else:
				i+=1
		Company.objects.bulk_create(companies)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def uploadStationService(request):
	if 'csv' in request.FILES:
		stationservices = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		i = 0
		for line in csv_file:
			if i != 0:
				station_service_code = line[3]
				station_code = Station.objects.get(station_code=line[4])
				station_name = line[5]
				line_service_name = line[10]
				line_service_code = LineService.objects.get(line_service_code=line[11])
				numbering_head = line[12]
				numbering_symbol = line[13]
				numbering_middle = line[14]
				numbering_number = line[15]
				sort_by_line_service = line[16]
				station_color = line[17]

				stationservice = StationService(
					station_service_code=station_service_code,
					station_code=station_code,
					station_name=station_name,
					line_service_name=line_service_name,
					line_service_code=line_service_code,
					numbering_head=numbering_head,
					numbering_symbol=numbering_symbol,
					numbering_middle=numbering_middle,
					numbering_number=numbering_number,
					sort_by_line_service=sort_by_line_service,
					station_color=station_color
					)
				stationservices.append(stationservice)
			else:
				i+=1
		StationService.objects.bulk_create(stationservices)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def uploadLineService(request):
	if 'csv' in request.FILES:
		lineservices = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		i = 0
		for line in csv_file:
			if i != 0:
				line_service_code = line[4]
				line_service_name_formal = line[5]
				line_service_name_formal_sub = line[6]

				company_name_simple = line[7]
				is_company_name = line[8]
				line_service_name = line[9]
				line_service_name_sub = line[10]
				company_code = Company.objects.get(company_code=line[14])
				sort_by_company = line[15]
				line_color = line[16]
				is_formal = line[17]
				is_service = line[18]
				lineservice = LineService(
					line_service_code=line_service_code,
					line_service_name_formal=line_service_name_formal,
					line_service_name_formal_sub=line_service_name_formal_sub,
					
					company_name_simple=company_name_simple,
					is_company_name=is_company_name,
					line_service_name=line_service_name,
					line_service_name_sub=line_service_name_sub,
					company_code=company_code,
					sort_by_company=sort_by_company,
					is_formal=is_formal,
					is_service=is_service,
					line_color=line_color)
				lineservices.append(lineservice)
			else:
				i+=1
		LineService.objects.bulk_create(lineservices)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def uploadRailwayType(request):
	if 'csv' in request.FILES:
		railwaytypes = []
		form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
		csv_file = csv.reader(form_data)
		for line in csv_file:
			railway_type_code_2 = line[0]
			railway_type_code = line[1]
			railway_type_name = line[2]
			railwaytype = Railway_type(railway_type_code_2=railway_type_code_2, railway_type_code=railway_type_code, railway_type_name=railway_type_name)
			railwaytypes.append(railwaytype)
		Railway_type.objects.bulk_create(railwaytypes)

		return render(request, 'ekimeidatanew/upload.html')

	else:
		return render(request, 'ekimeidatanew/upload.html')

def StationDelete(request):
	Station.objects.all().delete()
	return render(request, 'ekimeidatanew/upload.html')

def LineDelete(request):
	Line.objects.all().delete()
	return render(request, 'ekimeidatanew/upload.html')

def CompanyDelete(request):
	Company.objects.all().delete()
	return render(request, 'ekimeidatanew/upload.html')

def StationServiceDelete(request):
	StationService.objects.all().delete()
	return render(request, 'ekimeidatanew/upload.html')

def LineServiceDelete(request):
	LineService.objects.all().delete()
	return render(request, 'ekimeidatanew/upload.html')

class StationListbyLineView(generic.ListView):
	model = Line
	template_name = 'ekimeidatanew/stationlistbyline.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		line = Line.objects.get(line_code=self.kwargs['line_code'])
		stations = Station.objects.filter(line_code=self.kwargs['line_code'])
		transfers = {}
		for station in stations:
			transfers[station] = Station.objects.filter(station_group_code=station.station_group_code).exclude(line_code=line)
		context = {
			'line': line,
			'transfers': transfers
		}
		return context

class StationServiceListbyLineView(generic.ListView):
	model = LineService
	template_name = 'ekimeidatanew/stationservicelistbyline.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		lineservice = LineService.objects.get(line_service_code=self.kwargs['line_service_code'])
		stationservices = StationService.objects.filter(line_service_code=self.kwargs['line_service_code']).filter(station_code__e_status_old=0).order_by('sort_by_line_service')
		transfers = {}
		stationserviceprev = 0
		for stationservice in stationservices:
			if stationserviceprev != stationservice.station_code.station_group_code:
				transfers[stationservice] = {}
				transferstations = Station.objects.filter(station_group_code=stationservice.station_code.station_group_code)
				for transferstation in transferstations:

ekimeidatanew/templates/ekimeidatanew/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"> -->
	<link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" rel="stylesheet" />


	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	
	{% block content %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
		integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
		crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
		integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
		crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

ekimeidatanew/templates/ekimeidatanew/company.html
{% extends 'ekimeidatanew/base.html' %}

{% block title %}事業者一覧{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'ekimeidatanew/company.css' %}">

<div class="main-content">
	<a href="{% url 'ekimeidatanew:notice' %}">はじめにご覧ください</a>
	<p>駅名検索</p>
	<form action="{% url 'ekimeidatanew:stationsearchview' %}" method="get">
		<input type="text" name="q" value="{{ word }}">
		<button type="submit">検索</button>
	</form>
	<div class="title">事業者ごとの路線一覧</div>
	<ul class="company-ul">
		{% for company, lines in linebycompany.items %}
		<li class="company-li">
			<div class="company-name">{{ company }}</div>
			<ul class="line-ul">
				{% for line in lines %}
				<li class="line-li"><a href="{% url 'ekimeidatanew:stationservicelistbylineview' line.line_service_code %}">{{ line }}</a></li>
				{% endfor %}
			</ul>
		</li>
		{% endfor %}
	</ul>
	<small>&copy; 2020 nignagIC</small>
</div>
{% endblock %}

ekimeidatanew/templates/ekimeidatanew/stationlistbyline.html
{% extends 'ekimeidatanew/base.html' %}

{% block title %}{{ line }}{% endblock %}

{% block content %}
{{ line }}
<ul>
	{% for station, group_stations in transfers.items %}
		<li>{{ station }}</li>
		<ul>
		{% for group_station in group_stations %}
			<li>{{ group_station }} <a href="{% url 'ekimeidatanew:stationlistbylineview' group_station.line_code.line_code %}">{{ group_station.line_code }}</a>
		{% endfor %}
		</ul>
	{% endfor %}
	<small>&copy; 2020 nignagIC</small>
</ul>
{% endblock %}

ekimeidatanew/templates/ekimeidatanew/stationsearch.html
{% extends 'ekimeidatanew/base.html' %}

{% block title %}検索結果 - {{ word }}{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'ekimeidatanew/stationsearch.css' %}">
<div class="main-content">
	<p>駅名検索</p>
	<form action="{% url 'ekimeidatanew:stationsearchview' %}" method="get">
		<input type="text" name="q" value="{{ word }}">
		<button type="submit">検索</button>
	</form>
	<a href="{% url 'ekimeidatanew:lineservicelistbycompanyview' %}">路線一覧へ戻る</a>
	<h2>検索結果 - {{ word }} ({{ count }}件)</h2>
	<table>
		{% if stations %}
			{% for station in stations %}
			<tr>
				<td>{{ station }}</td>
				<td><a href="{% url 'ekimeidatanew:stationservicelistbylineview' station.line_service_code.line_service_code %}">{{ station.line_service_code }}</a><small> - {{ station.station_code.line_code.line_name }}</small></td>
			</tr>
			{% endfor %}
		{% else %}
			検索結果はありませんでした
		{% endif %}
	</table>
	<small>&copy; 2020 nignagIC</small>
</div>
{% endblock %}

ekimeidatanew/templates/ekimeidatanew/stationservicelistbyline.html
{% extends 'ekimeidatanew/base.html' %}

{% block title %}{{ lineservice }}{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'ekimeidatanew/stationservicelistbyline.css' %}">
<div class="main-content">
	<div class="line-name">{{ lineservice }}</div>
	<a href="{% url 'ekimeidatanew:lineservicelistbycompanyview' %}">路線一覧へ戻る</a>
	<ul class="line-ul">
		{% for stationservice, group_stationservices in transfers.items %}
		<li class="line-li">
			<div class="station-info" style="border-color: {{ stationservice.get_color }};">
				<div class="station-name">{{ stationservice }}</div>
				<div class="station-numbering">{{ stationservice.get_numbering }}</div>
			</div>
			<ul class="station-ul">
			{% for group_stationservice, transfers in group_stationservices.items %}
				<li class="station-li"><!-- <a href="{% url 'ekimeidatanew:stationlistbylineview' group_stationservice.line_code.line_code %}"> -->{{ group_stationservice.line_code }}<!-- </a> --></li>
				<ul class="service-ul">
				{% for transfer in transfers %}
					<li class="service-li">{{ transfer }} <a href="{% url 'ekimeidatanew:stationservicelistbylineview' transfer.line_service_code.line_service_code %}">{{ transfer.line_service_code }}</a></li>
				{% endfor %}
				</ul>
			{% endfor %}
			</ul>
		</li>
		{% endfor %}
	</ul>
	<small>&copy; 2020 nignagIC</small>
</div>
{% endblock %}

ekimeidatanew/templates/ekimeidatanew/upload.html
<head>
	<link rel='stylesheet' href="http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/css/dropify.css" />
	<script src="http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/js/dropify.js"></script>
</head>
<body>

<h3>アップロードするよ</h3>
<form action="{% url 'ekimeidatanew:uploadStation' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">駅名アップロード</button>
</form>

<form action="{% url 'ekimeidatanew:uploadLine' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">路線アップロード</button>
</form>

<form action="{% url 'ekimeidatanew:uploadCompany' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">事業者アップロード</button>
</form>

<form action="{% url 'ekimeidatanew:uploadRailwayType' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">路線種別アップロード</button>
</form>

<form action="{% url 'ekimeidatanew:uploadStationService' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">駅名(運行系統)アップロード</button>
</form>

<form action="{% url 'ekimeidatanew:uploadLineService' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">路線(運行系統)アップロード</button>
</form>

<a href="{% url 'ekimeidatanew:StationDelete' %}">駅全削除</a>
<a href="{% url 'ekimeidatanew:LineDelete' %}">路線全削除</a>
<a href="{% url 'ekimeidatanew:CompanyDelete' %}">事業者全削除</a>
<a href="{% url 'ekimeidatanew:StationServiceDelete' %}">駅(運行系統)全削除</a>
<a href="{% url 'ekimeidatanew:LineServiceDelete' %}">路線(運行系統)全削除</a>
<script>
$(function(){
  $('.dropify').dropify();
})
</script>
  <small>&copy; 2020 nignagIC</small>
</body>