ekimei1/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

from rest_framework import routers
router = routers.DefaultRouter()
# router.register('station', views.StationViewSet)
# router.register('line/<int:pref_cd>', views.LineViewSet.as_view(), base_name='lines')
urlpatterns = router.urls

app_name = 'ekimei1'

urlpatterns = [
	path('', views.Top.as_view(), name='top'),
	path('list/', views.MovieListView.as_view(), name="list"),
	path('detail/<slug:main_id>/', views.detail_movie, name='detail'),
	path('line/<int:line_cd>/', views.MovieListbyLineView.as_view(), name='line_list'),
	path('station/<int:station_cd>/', views.MovieListbyStationView.as_view(), name='station_list'),
	path('song/<int:id>/', views.MovieListbySongView.as_view(), name='song_list'),
	path('vocal/<int:id>/', views.MovieListbyVocalView.as_view(), name='vocal_list'),
	path('register/', views.MovieRegisterView.as_view(), name='register'),
	path('edit/<slug:main_id>/part/', views.part_edit, name='part_edit'),
	path('edit/<slug:main_id>/part/<int:part_num>/', views.station_edit, name='station_edit'),
	path('upload/', views.uploadStation, name='uploadStation'),
	path('uploadline/', views.uploadLine, name='uploadLine'),
	path('uploadpref/', views.uploadPref, name='uploadPref'),
	path('lineprefset/', views.lineprefset, name='lineprefset'),
	url('^api/line/(?P<pref_cd>.+)/$', views.LineViewSet.as_view()),
	url('^api/station/(?P<line_cd>.+)/$', views.StationViewSet.as_view()),
	url('^api/stationsearch/(?P<words>.+)/$', views.StationSearchViewSet.as_view()),
	url('^api/transfer/(?P<station_cd>.+)/$', views.TransferViewSet.as_view()),
	url('^api/partstation/(?P<id>.+)/$', views.PartStationViewSet.as_view()),
	url('api/name/', views.NameViewSet.as_view()),
	url('api/song/', views.SongViewSet.as_view()),
	url('api/vocal/', views.VocalViewSet.as_view()),
	# path('login/', views.Login.as_view(), name='login'),
	# path('logout/', views.Logout.as_view(), name='logout'),
	# path('user_create/', views.UserCreate.as_view(), name='user_create'),
	# path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
	# path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekimei1/', include('ekimei1.urls'), name='ekimei1'),
    path('ekimeidatanew/', include('ekimeidatanew.urls'), name='ekimeidatanew'),
]

ekimei1/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

class CustomUserManager(UserManager):
	user_in_migrations = True

	def _create_user(self, email, password, **extra_fields):
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self.db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')
		return self._create_user(email, password, **extra_fields)

# class User(AbstractBaseUser, PermissionsMixin):
# 	email = models.EmailField(_('email address'), unique=True)
# 	name = models.CharField(_('name'), max_length=100, blank=True)

# 	is_staff = models.BooleanField(
# 		_('staff status'),
# 		default=False,
# 		help_text=_(
# 			'Designates whether the user can log into this admin site.'),
# 	)
# 	is_active = models.BooleanField(
# 		_('active'),
# 		default=True,
# 		help_text=_(
# 			'Designates whether this user should be treated as active.'
# 			'Unselect this instead of deleting accounts.'
# 		),
# 	)
# 	date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
# 	objects = CustomUserManager()

# 	EMAIL_FIELD = 'email'
# 	USERNAME_FIELD = 'email'
# 	REQUIRED_FIELDS = []

# 	class Meta:
# 		verbose_name = _('user')
# 		verbose_name_plural = _('users')

# 	def email_user(self, subject, message, from_email=None, **kwargs):
# 		send_mail(subject, message, from_email, [self.email], **kwargs)

# 	@property
# 	def username(self):
# 		return self.email
	

class Prefecture(models.Model):
	pref_cd = models.IntegerField(default=0)
	pref_name = models.CharField(max_length=200)
	def __str__(self):
		return self.pref_name

class Line(models.Model):
	line_cd = models.IntegerField(default=0, unique=True)
	company_cd = models.IntegerField(default=0)
	line_name = models.CharField(max_length=200)
	line_name_k = models.CharField(max_length=200, null=True, blank=True)
	line_name_h = models.CharField(max_length=200, null=True, blank=True)
	line_color_c = models.CharField(max_length=200, null=True, blank=True)
	line_color_t = models.CharField(max_length=200, null=True, blank=True)
	line_type = models.CharField(max_length=200, null=True, blank=True)
	lon = models.CharField(max_length=200, null=True, blank=True)
	lat = models.CharField(max_length=200, null=True, blank=True)
	zoom = models.IntegerField(default=0)
	e_status = models.IntegerField(default=0)
	e_sort = models.IntegerField(default=0)
	pref_cds = models.ManyToManyField(Prefecture, blank=True)
	def __str__(self):
		return self.line_name_h

class Station(models.Model):
	station_cd = models.IntegerField('駅コード', default=0, unique=True)
	station_g_cd = models.IntegerField('駅グループコード', default=0)
	station_name = models.CharField('駅名', max_length=200)
	station_name_k = models.CharField('駅名(カナ)', max_length=200, null=True, blank=True)
	station_name_r = models.CharField('駅名(ローマ字)', max_length=200, null=True, blank=True)
	line_cd = models.ForeignKey(Line, to_field='line_cd', null=True, blank=True, on_delete=models.CASCADE, verbose_name='路線')
	pref_cd = models.ForeignKey(Prefecture, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='都道府県')
	post = models.CharField('駅郵便番号', max_length=200, null=True, blank=True)
	add = models.CharField('住所', max_length=200, null=True, blank=True)
	lon = models.CharField('経度', max_length=200, null=True, blank=True)
	lat = models.CharField('緯度', max_length=200, null=True, blank=True)
	open_ymd = models.DateField('開業年月日', max_length=200, null=True, blank=True)
	close_ymd = models.DateField('廃止年月日', max_length=200, null=True, blank=True)

	STATUS = (
		(0, '運用中'),
		(1, '運用前'),
		(2, '廃止')
	)
	e_status = models.IntegerField('状態', choices=STATUS, default=0)
	e_sort = models.IntegerField('並び順', default=0)
	def __str__(self):
		return self.station_name

class Station2(models.Model):
	station_cd = models.IntegerField('駅コード', default=0, unique=True)
	station_g_cd = models.IntegerField('駅グループコード', default=0)
	station_name = models.CharField('駅名', max_length=200)
	station_name_k = models.CharField('駅名(カナ)', max_length=200, null=True, blank=True)
	station_name_r = models.CharField('駅名(ローマ字)', max_length=200, null=True, blank=True)
	line_cd = models.ForeignKey(Line, to_field='line_cd', null=True, blank=True, on_delete=models.CASCADE, verbose_name='路線')
	pref_cd = models.ForeignKey(Prefecture, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='都道府県')
	post = models.CharField('駅郵便番号', max_length=200, null=True, blank=True)
	add = models.CharField('住所', max_length=200, null=True, blank=True)
	lon = models.CharField('経度', max_length=200, null=True, blank=True)
	lat = models.CharField('緯度', max_length=200, null=True, blank=True)
	open_ymd = models.DateField('開業年月日', max_length=200, null=True, blank=True)
	close_ymd = models.DateField('廃止年月日', max_length=200, null=True, blank=True)

	STATUS = (
		(0, '運用中'),
		(1, '運用前'),
		(2, '廃止')
	)
	e_status = models.IntegerField('状態', choices=STATUS, default=0)
	e_sort = models.IntegerField('並び順', default=0)
	def __str__(self):
		return self.station_name

class Category(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return self.name

class Creator(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return self.name

class YoutubeChannel(models.Model):
	name = models.CharField(max_length=200)
	channelId = models.CharField(max_length=200, primary_key=True)
	creator = models.ForeignKey(Creator, on_delete=models.SET_NULL, null=True, related_name='channel', verbose_name='作者')
	def __str__(self):
		return self.name

class Name(models.Model):
	#名義(合作、単作関わらずこの名前で参加者を記述)
	name = models.CharField(max_length=200)
	creator = models.ForeignKey(Creator, on_delete=models.SET_NULL, null=True, blank=True, related_name='part_name', verbose_name='作者')
	def __str__(self):
		return self.name

class Artist(models.Model):
	name = models.CharField(max_length=200)
	parent = models.ManyToManyField('self', verbose_name='所属グループ等', blank=True)
	def __str__(self):
		return self.name

class Song(models.Model):
	name = models.CharField('曲名', max_length=200)
	namerb = models.CharField('曲名カナ', max_length=200, blank=True)
	artist = models.ManyToManyField(Artist, blank=True)
	album = models.CharField('アルバム名', max_length=200, blank=True)
	lyrist = models.CharField('作詞者', max_length=200, blank=True)
	composer = models.CharField('作曲者', max_length=200, blank=True)
	tieup = models.CharField('タイアップ等', max_length=200, blank=True)
	description = models.TextField('備考', max_length=500, blank=True)
	parent = models.ManyToManyField('self', verbose_name='原作等', blank=True)
	def __str__(self):
		return self.name

class Vocal(models.Model):
	name = models.CharField('ボーカル名', max_length=200)
	def __str__(self):
		return self.name

class Movie(models.Model):
	title = models.CharField('動画タイトル', max_length=200)
	channel = models.ForeignKey(
		YoutubeChannel, on_delete=models.SET_NULL, null=True, verbose_name='投稿チャンネル'
	)
	participant = models.ManyToManyField(
		Name, blank=True, verbose_name='参加者'
	)
	main_id = models.CharField('動画ID', max_length=200, unique=True)
	youtube_id = models.CharField('YouTubeのID', max_length=200, blank=True)
	niconico_id = models.CharField('ニコニコ動画のID', max_length=200, blank=True)
	published_at = models.DateTimeField('投稿日時', blank=True, null=True)
	duration = models.DurationField('動画の長さ', null=True)
	n_view = models.IntegerField('再生回数', default=0, blank=True)
	n_like = models.IntegerField('高評価数', default=0, blank=True)
	n_dislike = models.IntegerField('低評価数', default=0, blank=True)
	n_comment = models.IntegerField('コメント数', default=0, blank=True)
	description = models.TextField('説明', blank=True)

	reg_date = models.DateTimeField('データベース登録日時', blank=True)

	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='カテゴリー')
	song = models.ManyToManyField(Song, blank=True, verbose_name='使用楽曲')
	vocal = models.ManyToManyField(Vocal, blank=True, verbose_name='使用ボーカル')
	COLLAB = (
		('S', '単作'),
		('C', '合作')
	)
	is_collab = models.CharField('合作か', max_length=1, choices=COLLAB, default='S')
	parent = models.ManyToManyField('self', verbose_name='親作品', blank=True)
	explanation = models.TextField('補足説明', blank=True)
	def __str__(self):
		return self.title

class Part(models.Model):
	part_num = models.IntegerField()
	part_name_short = models.CharField(max_length=5)
	part_name = models.CharField(max_length=200, blank=True)
	movie = models.ForeignKey(Movie, to_field='main_id', on_delete=models.CASCADE)
	participant = models.ManyToManyField(Name, blank=True, verbose_name='参加名義')
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='カテゴリー')
	start_time = models.DurationField('開始時間', null=True, blank=True)
	song = models.ManyToManyField(Song, blank=True, verbose_name='使用楽曲')
	song_name = models.CharField(max_length=200, blank=True)
	vocal = models.ManyToManyField(Vocal, blank=True, verbose_name='使用ボーカル')
	explanation = models.TextField('説明', blank=True)
	def __str__(self):
		return self.part_name + " - " + self.movie.title

class StationInMovie(models.Model):

ekimei1/forms.py
from django.forms import Form, ModelForm, inlineformset_factory
from django import forms
from .models import Movie, Part, StationInMovie

# from django.contrib.auth.forms import (
# 	AuthenticationForm
# )

# class LoginForm(AuthenticationForm):
# 	def __init__(self, *args, **kwargs):
# 		super().__init__(*args, **kwargs)
# 		for field in self.fields.values():
# 			field.widget.attrs['class'] = 'form-control'
# 			field.widget.attrs['placeholder'] = field.label

class MovieRegisterForm(forms.ModelForm):
	class Meta:
		model = Movie
		fields = ('title', 'channel', 'main_id', 'youtube_id', 'niconico_id', 'published_at', 'duration', 'n_view', 'n_like', 'n_dislike', 'n_comment', 'description', 'reg_date', 'is_collab', 'parent')
		widgets = {
			'title': forms.HiddenInput(attrs={
				'class': 'title',
			}),
			'channel': forms.HiddenInput(attrs={
				'id': 'channel',
			}),
			'main_id': forms.HiddenInput(attrs={
				'class': 'main_id',
			}),
			'youtube_id': forms.HiddenInput(attrs={
				'class': 'youtube_id',
			}),
			'niconico_id': forms.HiddenInput(attrs={
				'class': 'niconico_id',
			}),
			'published_at': forms.HiddenInput(attrs={
				'class': 'published_at',
			}),
			'duration': forms.HiddenInput(attrs={
				'class': 'duration',
			}),
			'n_view': forms.HiddenInput(attrs={
				'class': 'n_view',
			}),
			'n_like': forms.HiddenInput(attrs={
				'class': 'n_like',
			}),
			'n_dislike': forms.HiddenInput(attrs={
				'class': 'n_dislike',
			}),
			'n_comment': forms.HiddenInput(attrs={
				'class': 'n_comment',
			}),
			'description': forms.HiddenInput(attrs={
				'class': 'description',
			}),
			'reg_date': forms.HiddenInput(attrs={
				'class': 'reg_date',
			}),
		}

class MovieUpdateForm(forms.ModelForm):
	class Meta:
		model = Movie
		fields = ('title', 'channel', 'main_id', 'youtube_id', 'niconico_id', 'published_at', 'duration', 'n_view', 'n_like', 'n_dislike', 'n_dislike', 'n_comment', 'description', 'reg_date', 'song', 'vocal', 'is_collab')
		widgets = {
			'title': forms.HiddenInput(attrs={
				'class': 'title',
			}),
			'channel': forms.HiddenInput(attrs={
				'id': 'channel',
			}),
			'main_id': forms.HiddenInput(attrs={
				'class': 'main_id',
			}),
			'youtube_id': forms.HiddenInput(attrs={
				'class': 'youtube_id',
			}),
			'niconico_id': forms.HiddenInput(attrs={
				'class': 'niconico_id',
			}),
			'published_at': forms.HiddenInput(attrs={
				'class': 'published_at',
			}),
			'duration': forms.HiddenInput(attrs={
				'class': 'duration',
			}),
			'n_view': forms.HiddenInput(attrs={
				'class': 'n_view',
			}),
			'n_like': forms.HiddenInput(attrs={
				'class': 'n_like',
			}),
			'n_dislike': forms.HiddenInput(attrs={
				'class': 'n_dislike',
			}),
			'n_comment': forms.HiddenInput(attrs={
				'class': 'n_comment',
			}),
			'description': forms.HiddenInput(attrs={
				'class': 'description',
			}),
			'reg_date': forms.HiddenInput(attrs={
				'class': 'reg_date',
			}),
		}

class PartEditForm(forms.ModelForm):
	class Meta:
		model = Part
		fields = ('part_num', 'part_name_short', 'part_name', 'movie', 'participant', 'category', 'start_time', 'song', 'song_name', 'vocal', 'explanation')
		widgets = {
			'part_num': forms.HiddenInput(attrs={
				'class': 'part_num',
			}),
			'part_name_short': forms.HiddenInput(attrs={
				'class': 'part_name_short',
			}),
			'part_name': forms.HiddenInput(attrs={
				'class': 'part_name',
			}),
			'movie': forms.HiddenInput(attrs={
				'class': 'movie',
			}),
			'participant': forms.SelectMultiple(attrs={
				'class': 'participant',
			}),
			'category': forms.Select(attrs={
				'class': 'category',
			}),
			'start_time': forms.HiddenInput(attrs={
				'class': 'start_time',
			}),
			'song': forms.SelectMultiple(attrs={
				'class': 'song',
			}),
			'song_name': forms.HiddenInput(attrs={
				'class': 'song_name',
			}),
			'vocal': forms.SelectMultiple(attrs={
				'class': 'vocal',
			}),
			'explanation': forms.HiddenInput(attrs={
				'class': 'explanation',
			}),
		}

PartEditFormset = forms.inlineformset_factory(
	parent_model = Movie,
	model = Part,
	form = PartEditForm,
	extra = 1,
	can_delete = True,
	can_order = True
)

class StationInMovieEditForm(forms.ModelForm):
	BACKREL_CHOICES = [
		(0, '同一駅'),
		(1, 'つながっている'),
		(2, '離れている'),
	]
	id_in_movie = forms.IntegerField(
		label='順番', widget=forms.HiddenInput
	)
	back_rel = forms.ChoiceField(
		label='前駅関係', choices=BACKREL_CHOICES, widget=forms.Select
	)
	station_name = forms.CharField(
		label='歌唱名', max_length=50
	)
	class Meta:
		model = StationInMovie
		fields = ('id_in_movie', 'movie_part', 'station_cd', 'station_name', 'non_line', 'back_rel')
		widgets = {
			'id_in_movie': forms.TextInput(attrs={
				'class': 'id_in_movie',
			}),
			'movie_part': forms.Select(attrs={
				'class': 'movie_part',
			}),
			'station_cd': forms.HiddenInput(attrs={
				'class': 'station_cd',
			}),
			'station_name': forms.TextInput(attrs={
				'class': 'station_name',
			}),
			'non_line': forms.CheckboxInput(attrs={
				'class': 'non_line',
			}),
			'back_rel': forms.TextInput(attrs={
				'class': 'back_rel',
			}),
		}

StationInMovieEditFormset = forms.inlineformset_factory(
	parent_model = Part,
	model = StationInMovie,
	form = StationInMovieEditForm,
	extra = 0,
	can_delete = False
)

ekimei1/templates/ekimei1/detail_uncompleted.html
{% extends 'ekimei1/base.html' %}
{% load widget_tweaks %}
{% load tags %}

{% block title %}{{ movie }} - 詳細{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'ekimei1/detail.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<p><a href="{% url 'ekimei1:list' %}">リストへ戻る</a></p>
<div class="main-container">
	<div class="movie-detail">
		<div class="youtube-container">
			<div class="youtube">
				<iframe src="https://www.youtube.com/embed/{{ movie.main_id }}"  frameborder='0' gesture='media' allowfullscreen></iframe>
			</div>
		</div>
		<div class="detail-original">
			<a href="https://www.youtube.com/watch?v={{ movie.youtube_id }}" target="_blank" class="movie-title-link"><h2 class="movie-title">{{ movie.title }}</h2></a>
			<div class="movie-channel">{{ movie.channel }}</div>
			<div class="detail-addition">
				{% if movie.song.all %}
				<h3 class="detail-song-header">使用楽曲</h3>
					{% for song in movie.song.all %}
					<p><a href="{% url 'ekimei1:song_list' song.id %}">{{ song }}</a>
						{% if song.artist %}
							{% for artist in song.artist.all %}
							<a href=""> - {{ artist }}</a>
							{% endfor %}
						{% endif %}
					</p>
					{% endfor %}
				{% endif %}
				{% if movie.vocal.all %}
				<h3 class="detail-vocal-header">使用ボーカル</h3>
					{% for vocal in movie.vocal.all %}
					<p><a href="{% url 'ekimei1:vocal_list' vocal.id %}">{{ vocal }}</a></p>
					{% endfor %}
				{% endif %}
			</div>
			<h3 class="movie-published-header">投稿日時</h3>
			<table class="movie-published">
				<tbody>
					<tr>
						<td>世界標準時</td>{% load tz %}
						<td class="movie-published-iso">{{ movie.published_at|utc|date:"Y年Nd日 H:i:s" }}</td>
					</tr>
					<tr>
						<td>日本時間</td>
						<td class="movie-published-jpn">{{ movie.published_at|date:"Y年Nd日 H:i:s" }}</td>
					</tr>
				</tbody>
			</table>
			<div class="movie-statistics">
				<div class="movie-statistics-item">
					<div class="movie-statistics-num">
					{% if n_view == 0 %}
						0
					{% else %}
						{{ movie.n_view }}
					{% endif %}</div>
					<div class="movie-statistics-name">再生回数</div>
				</div>
				<div class="movie-statistics-item">
					<div class="movie-statistics-num">
					{% if n_like == 0 %}
						0
					{% else %}
						{{ movie.n_like }}
					{% endif %}</div>
					<div class="movie-statistics-name">高評価数</div>
				</div>
				<div class="movie-statistics-item">
					<div class="movie-statistics-num">
					{% if n_dislike == 0 %}
						0
					{% else %}
						{{ movie.n_dislike }}
					{% endif %}
					</div>
					<div class="movie-statistics-name">低評価数</div>
				</div>
				<div class="movie-statistics-item">
					<div class="movie-statistics-num">
					{% if n_comment == 0 %}
						0
					{% else %}
						{{ movie.n_comment }}
					{% endif %}</div>
					<div class="movie-statistics-name">コメント数</div>
				</div>
			</div>
			<div class="movie-description-container">
				<p id="movie-description"></p>
			</div>
		</div>
		<div class="related-movie">
		</div>
	</div>
	<div class="movie-station-list">
		{% for stationofpart in stations %}
			{{ stationofpart.0.0.movie_part.part_name_short }}
			{% for participant in stationofpart.0.0.movie_part.participant.all %}
				{{ participant }}
			{% endfor %}
			{{ stationofpart.0.0.movie_part.start_time }}
			{{ stationofpart.0.0.movie_part.song_name }}
			{% for song in stationofpart.0.0.movie_part.song.all %}
				<a href="{% url 'ekimei1:song_list' song.id %}">{{ song }}</a>
			{% endfor %}
			{% for vocal in stationofpart.0.0.movie_part.vocal.all %}
				<a href="{% url 'ekimei1:vocal_list' vocal.id %}">{{ vocal }}</a>
			{% endfor %}
			{{ stationofpart.0.0.movie_part.explanation }}
				{% for stationofline in stationofpart %}
				{% if stationofpart.0.0.movie_part.category.name != "駅名替え歌" %}
				<h4 class="movie-line-name">{{ stationofline.0.station_cd.line_cd }}</h4>
				{% endif %}
					<ul>
					{% for station in stationofline %}
						<li class="station-name">
							<a href="{% url 'ekimei1:station_list' station.station_cd.station_cd %}">{{ station }}
							{% if stationofpart.0.0.movie_part.category.name == "駅名替え歌" %}
							 - {{ station.station_cd.line_cd }}
							 {% endif %}
							</a>
						</li>
					{% endfor %}
					</ul>
				{% endfor %}
		{% endfor %}
	</div>
</div>
{% endblock %}

ekimei1/templates/ekimei1/login.html
{% extends "ekimei1/base.html" %}
{% block content %}
<form action="" method="POST">
	<div>
		{{ form.non_field_errors }}
		{% for field in form %}
			{{ field }}
			{{ field.errors }}
		{% endfor %}
		<button type="submit">ログイン</button>
		<input type="hidden" name="next" value="{{ next }}" />
		{% csrf_token %}
	</div>
</form>
{% endblock %}

ekimei1/templates/ekimei1/moviebylinelist.html
{% extends 'ekimei1/base.html' %}

{% block title %}動画一覧 - {{ line }}{% endblock %}

{% block content %}
{{ line.line_name }}を含む駅名動画
<ul>
	<!-- {% for stations in moviebystationlist %}
		{{ station_matches.y.line_cd }}
		{% if stations %}
			{% for station in stations %}
			<li><a href="/ekimei1/movie/{{ station.movie.main_id }}/">{{ station.movie }}</a></li>
			{% endfor %}
			<br>
		{% endif %}
	{% endfor %} -->
	{% for movie in movies %}
		<ul>
			<li><a href="{% url 'ekimei1:detail' movie.main_id %}">{{ movie.title }}</a></li>
		</ul>
	{% endfor %}
	{% for station in line.station_set.all %}
		<a href="{% url 'ekimei1:station_list' station.station_cd %}">{{ station }}</a>
	{% endfor %}
</ul>
{% endblock %}

ekimei1/templates/ekimei1/moviebystationlist.html
{% extends 'ekimei1/base.html' %}

{% block title %}動画一覧 - {{ stations.0.station_name }}駅{% endblock %}

{% block content %}
{{ stations.0.station_name }}を含む駅名動画
<ul>
	{% for station in stations %}
		{{ station }} - <a href="{% url 'ekimei1:line_list' station.line_cd.line_cd %}">{{ station.line_cd }}</a>
		<ul>
		{% for stationinmovie in station.stationinmovie_set.all %}
			<li><a href="{% url 'ekimei1:detail' stationinmovie.movie_part.movie.main_id %}">{{ stationinmovie.movie_part.movie }}</a></li>
		{% endfor %}
		</ul>
	{% endfor %}
</ul>
{% endblock %}

ekimei1/templates/ekimei1/upload.html
<head>
	<link rel='stylesheet' href="http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/css/dropify.css" />
	<script src="http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/js/dropify.js"></script>
</head>
<body>

<h3>アップロードするよ</h3>
<form action="{% url 'ekimei1:uploadStation' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">駅名アップロード</button>
</form>

<form action="{% url 'ekimei1:uploadLine' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">路線アップロード</button>
</form>

<form action="{% url 'ekimei1:uploadPref' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">都道府県アップロード</button>
</form>
<script>
$(function(){
  $('.dropify').dropify();
})
</script>
</body>